[package]
name = "easy-stress-rs"
version = "0.1.0"
authors = ["Damon Montague Jr"]
edition = "2021"

[dependencies]
inquire = "0.5.3"
sysinfo = "0.27.6"
colored = "2"
ctrlc = { version = "3.0", features = ["termination"] }
ocl = "0.19.4"
strum = { version = "0.24", features = ["derive"] }