[package]
name = "easy-stress-rs"
version = "2.0.1"
authors = ["Damon Montague Jr"]
repository = "https://github.com/day-mon/easy-stress-rs"
edition = "2021"

[dependencies]
inquire = "0.5.3"
sysinfo = "0.27.6"
colored = "2"
ocl = "0.19.4"
